# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    links:
      - db:db
    ports:
      - '8081:8080'
